Allow merging configs with different types of leaf values
spf13/viper pull request #1181
Opened 2021-08-08 08:21 UTC by illarion

This fixes the problem that appears when your base config has values with different type than the override, which is valid use case.

2021-08-29 16:48 UTC, illarion commented
@spf13 are there any plans on including this patch? We depend on it in our production and would like to have it fixed. Thank you

2021-09-16 08:29 UTC, sagikazarmark requested changes

2021-09-16 08:29 UTC, sagikazarmark commented on viper.go
> -		}
Is there a test that makes sure this behavior hasn't changed? If not, can you please add one?

2021-12-19 14:20 UTC, sagikazarmark requested changes
@illarion can you please rebase the PR?

2021-12-20 10:33 UTC, illarion commented
Sure

2021-12-20 10:49 UTC, illarion commented
@sagikazarmark rebased, please review

2022-01-11 21:36 UTC, sagikazarmark approved these changes
Thanks @illarion !

2022-01-11 21:36 UTC, merged