Adds support for uint16 with `GetUint16`
spf13/viper pull request #1405
Opened 2022-07-19 08:00 UTC by oxisto

We have encountered numerous places where it is convenient to have viper return a `uint16` value, especially in combination with the new `netip` package  that represents a port correctly as `uint16` rather than just an `int`. cobra already supports this, but we need a conversion from the existing `GetUint` method in viper.

2022-07-19 08:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/viper?pullRequest=1405) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/viper?pullRequest=1405) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/viper?pullRequest=1405) it.</sub>

2022-09-03 15:41 UTC, sagikazarmark approved these changes
LGTM, thanks @oxisto

2022-09-03 15:47 UTC, sagikazarmark requested changes
@oxisto actually, can you please rebase your PR to trigger CI?

2022-09-03 17:57 UTC, oxisto commented
> @oxisto actually, can you please rebase your PR to trigger CI?

done.

2022-09-04 01:07 UTC, sagikazarmark approved these changes
Thanks!

2022-09-04 01:07 UTC, merged