Allow BindEnv to register multiple environment variables.
spf13/viper pull request #972
Opened 2020-09-10 10:10 UTC by gbbr

This change modifies BindEnv to permit a list of environment variable
names in order to support multiple env. vars. for the same config key.
When this form is used, env. keys take precedence in the written order.

Closes #971

2020-09-10 10:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/spf13/viper?pullRequest=972) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/spf13/viper?pullRequest=972) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/spf13/viper?pullRequest=972) it.</sub>

2020-09-23 22:04 UTC, sagikazarmark approved these changes
Thanks!

2020-09-23 22:05 UTC, sagikazarmark requested changes
Actually @gbbr would you mind adding some documentation about this feature:
- to the `BindEnv` function header
- to the README

Thanks!

2020-09-29 16:53 UTC, sagikazarmark commented
Ping @gbbr

2020-09-30 10:25 UTC, gbbr commented
Done. Let me know what you think.

2020-09-30 10:44 UTC, sagikazarmark approved these changes
LGTM, thanks!

2020-09-30 10:44 UTC, merged